### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by jburel**
* update insight and napari
* change image id to show labels in napari

### CODE REVIEW

**Comment by pwalczysko** [comment]
How to test this ?

**Comment by jburel** [comment]
Run locally or on mybinder the notebook napari_s3.ipynb

**Comment by joshmoore** [comment]
@jburel : perhaps https://mybinder.readthedocs.io/en/latest/howto/gh-actions-badges.html ?

**Comment by jburel** [comment]
i am planning to start pushing GH to various guides repo.
This is certainly a good one

**Comment by pwalczysko** [comment]
Ran in mybinder and all was working, except in napari, the image is kind of cropped.

Screen Shot 2020-11-10 at 17 50 05

**Comment by jburel** [comment]
that's not related to this PR that will be a napari problem

**Comment by pwalczysko** [comment]
But I see it also in the ilastik notebook. Note that the blastocyst on the screenshot below is "cut off" very similarly to the one here in napari. The screenshot is taken after the jupyter notebook https://github.com/ome/omero-guide-ilastik/pull/22/files#diff-54c76e03d425145934a460d0cc7ad23c67dbd577e7fb8bf7b42dee58e6c66804
I saw this both on mybinder and local repo2docker build versions with ilastik. The cut-off seems very similar in size to the napari one here.

Screen Shot 2020-11-11 at 12 59 57

**Comment by jburel** [comment]
I don't so something might be happening in the display

**Comment by pwalczysko** [comment]
> I don't so something might be happening in the display

you mean you do not see this cut-off on your machine ?

**Comment by jburel** [comment]
I mean we look at one channel, but all the z-sections should be loaded

**Comment by jburel** [comment]
@will-moore did you notice similar behaviour in your tests? It could be a problem with the file itself
since both napari and itk viewer are showing similar things

**Comment by pwalczysko** [comment]
Re: truncation of the image comment 

The image is http://idr.openmicroscopy.org/webclient/?show=image-6001247, not the B1_C1 which I thought it is. This is fine, as the http://idr.openmicroscopy.org/webclient/?show=image-6001247 is really truncated in IDR.

Ready to merge fmpov.

**Pull request merged**
