### PR TITLE
Vnc

### PR DESCRIPTION
**Pull request by jburel**
This PR fixes the installation of novnc. The file is no longer available at https://bintray.com/tigervnc/stable/download_file?file_path=tigervnc-1.9.0.x86_64.tar.gz.
This stops working over the weekend

This PR also installed dependencies from conda-forge channel

* Check that the desktop can be started.
* Check a notebook

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
On MyBinder

1. Desktop started with no probs
2. The notebook ``napari``   produced an error

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-c20f4b86e8de> in <module>
      1 from dask import delayed
      2 import dask.array as da
----> 3 import napari
      4 from vispy.color import Colormap
      5 import numpy

/srv/conda/envs/notebook/lib/python3.7/site-packages/napari/__init__.py in <module>
      5 
      6 
----> 7 from .viewer import Viewer  # isort:skip
      8 
      9 # this unused import is here to fix a very strange bug.

/srv/conda/envs/notebook/lib/python3.7/site-packages/napari/viewer.py in <module>
      1 from typing import TYPE_CHECKING
      2 
----> 3 from .components import ViewerModel
      4 from .utils import config
      5 

/srv/conda/envs/notebook/lib/python3.7/site-packages/napari/components/__init__.py in <module>
     15 """
     16 
---> 17 from .camera import Camera
     18 from .dims import Dims
     19 from .layerlist import LayerList

/srv/conda/envs/notebook/lib/python3.7/site-packages/napari/components/camera.py in <module>
      1 from typing import Tuple
      2 
----> 3 from pydantic import validator
      4 
      5 from ..utils.events import EventedModel

ModuleNotFoundError: No module named 'pydantic'
```

**Comment by jburel** [comment]
Ok. The problem is not the desktop which what this PR fixes.
I will look into updating napari

**Comment by jburel** [comment]
@pwalczysko The problem should now be fixed

**Comment by pwalczysko** [comment]
The run of the napari notebook went through without a problem this time. I can see a running napari in the Desktop with some image in it.

Ready to merge fmpov..

**Pull request merged**
